### ISSUE TITLE
Gradle 5.0 will remove a JavaLibrary constructor.

### ISSUE THREAD

**Issue by gki** [LemonadeLabInc/gradle-snippets#11]
gradleのバージョンアップ作業中に出てきたワーニングの備忘。

> A constructor for `org.gradle.api.internal.java.JavaLibrary` is used by Shadow plugin v1.2.x, and has been preserved for compatibility. This has been deprecated and is scheduled to be removed in Gradle 5.0. If you're using the Shadow plugin, try upgrading to v2.x.

https://github.com/LemonadeLabInc/gradle-snippets/blob/1bba46334b0fb3df5778b2bdfec9c91fbf6bb0b7/src/main/groovy/de/lemona/gradle/plugins/PublishPlugin.groovy#L99

**Comment by tkcmrc** [comment]
Fixed by #14
